### PR TITLE
Allow server-side encryption

### PR DESCRIPTION
**Pull request by eltos**
Closes https://github.com/pulsejet/memories/issues/99

### CODE REVIEW

**Comment by pulsejet** [comment]
Thanks for digging into this. This looks fine to me, as long as you tested it. If `updateExifDate` also works as you mentioned, you can just move the same check to `Utils` and call it from `ImageController` (and get rid of the check in `updateExifDate`).

**Comment by pulsejet** [comment]
Just to be sure, this is tested on at least Nextcloud 24?

**Comment by eltos** [comment]
Tested it on NC 24 back then, just tested on NC 25.0.1 again.

**Comment by pulsejet** [comment]
Thank you! I'll take it from here.

**Pull request closed without merging**
