### PR TITLE
[Indexing] Continue to next file on value errors

### PR DESCRIPTION
**Pull request by akhil1508**
https://github.com/pulsejet/memories/issues/820

### CODE REVIEW

**Comment by akhil1508** [comment]
```
root@ncserver /path/to/nextcloud # occ memories:index -u johndoe --folder=/ --skip-cleanup
Indexing user johndoe
Indexing file /johndoe/files/InstantUpload/Pictures/photo-01.jpg
Failed to index file /johndoe/files/InstantUpload/Pictures/photo-02.jpg: fread(): Argument #2 ($length) must be greater than 0
Indexing file /johndoe/files/InstantUpload/Pictures/photo-03.jpg
Failed to index file /johndoe/files/InstantUpload/Pictures/photo-03.jpg: fread(): Argument #2 ($length) must be greater than 0
Indexing file /johndoe/files/InstantUpload/Pictures/photo-04.jpg
Failed to index file /johndoe/files/InstantUpload/Pictures/photo-04.jpg: fread(): Argument #2 ($length) must be greater than 0
Indexing file /johndoe/files/InstantUpload/Pictures/photo-05.jpg
Failed to index file /johndoe/files/InstantUpload/Pictures/photo-05.jpg: fread(): Argument #2 ($length) must be greater than 0
Indexing file /johndoe/files/InstantUpload/Pictures/photo-06.jpg
Indexing file /johndoe/files/InstantUpload/Pictures/photo-07.jpg
Indexing file /johndoe/files/InstantUpload/Pictures/photo-08.jpg
Indexing file /johndoe/files/InstantUpload/Pictures/photo-09.jpg
Failed to index file /johndoe/files/InstantUpload/Pictures/photo-09.jpg: fread(): Argument #2 ($length) must be greater than 0
root@ncserver /path/to/nextcloud #
```

After adding the patch, output looks like :point_up:

**Comment by pulsejet** [comment]
I'd prefer fixing this error rather than suppressing it. Can you provide a file for which this happens?

**Comment by akhil1508** [comment]
These are usually file entries left from upload errors. Not an issue of memories IMO than a nextcloud issue, does not make sense that the entire indexing job fails because of this.   
  

  
I'm currently afk but I do provide you more details later.   
  

  

  

  
  
  
  
  
>

**Comment by pulsejet** [comment]
Interesting. Still I'd prefer a more specific try-catch or (better) fix this upstream. Can you produce a stack trace?

**Comment by pulsejet** [comment]
Is this #820?

**Comment by pulsejet** [comment]
@akhil1508 this might be fixed in the latest stable, can you still reproduce this?

**Comment by akhil1508** [comment]
> this might be fixed in the latest stable, can you still reproduce this?

@pulsejet Latest stable of memories?  I need to check and get back as I did apply a patch to ensure these "bad" files don't stop indexing job(and I have a lot of media still left to index..)

**Comment by pulsejet** [comment]
> Latest stable of memories?

yes.

**Pull request closed without merging**
