### PR TITLE
Adds uploading button and uploading modal

### LINKED ISSUE #69: Make it possible to upload photos directly from the app
In the upcoming photo app 25, nextcloud get an option to  upload photos from the photo app.
It would be nice to have such option in memories also.

### PR DESCRIPTION
**Pull request by johnSamilin**
DRAFT

fixes #69 

- Upgraded @nextcloud/vue to 8 version
- Added UploadModal component
- Added button to sidebar
- Photos are being uploaded to the current folder (or `/` by default)

I'll appreciate any help with testing.

### CODE REVIEW

**Comment by pulsejet** [comment]
Great! Can you please clean up your diff? You seem to have some issue with the prettier configuration (wrong version?) which makes it impossible to review this.

**Comment by pulsejet** [comment]
> Upgraded @nextcloud/vue to 8 version

See #1060. I believe the patch is merged in the new version but this is still very high risk right now.

> Photos are being uploaded to the current folder (or / by default)

This will need to be configurable; definitely don't want them going to `/`

**Comment by johnSamilin** [comment]
@pulsejet @nextcloud/vue 8 is a necessity because @nextcloud/upload requires it

**Comment by pulsejet** [comment]
I see. Does it still work on 27 then? The target is to support at least two prior versions.

**Comment by pulsejet** [comment]
@johnSamilin I'll likely carry this forward in a separate branch. Thanks for the contribution!

**Comment by johnSamilin** [comment]
@pulsejet got it. I hope this PR was helpful. If not, sorry, I'm not very familiar with nextcloud and vue still

**Comment by pulsejet** [comment]
Yup, I just built over this :)

**Comment by ChildLearningClub** [comment]
The upload button appears when sharing the album as public link, but nowhere within the Memories settings or when creating the public link can I see the options to configure what the button does. At this point, at least with public link albums on iOS Safari, the button does nothing when pressed. When logged in it does work, but not clear where the photos go.

**Comment by pulsejet** [comment]
> The upload button appears when sharing the album as public link

Ah that's a bug. Upload only works when logged in.

> When logged in it does work, but not clear where the photos go.

It prompts you where to store the files. The default is either the timeline path (the first one) or the current folder if you're in the folders view.

image

**Comment by ChildLearningClub** [comment]
Okay, I see that now when I'm on the desktop Brave browser, but I'm given no such option when logged in on iOS Safari and uploading using that button.

**Comment by ChildLearningClub** [comment]
edit wait... now it just popped up.

**Comment by ChildLearningClub** [comment]
although in a future release the functionality to upload via public links would probably be wanted and would be per album. Those options could be put in under the "Share Album" section when sharing the album.

**Comment by pulsejet** [comment]
> although in a future release the functionality to upload via public links would probably be wanted and would be per album

That'll be nice yeah. It's actually relatively straightforward for folder shares; albums are more work because of the need to specify where the files would go (and this would likely need support from Photos too)

**Pull request closed without merging**
