### PR TITLE
Support for place list with reverse geocoding

### PR DESCRIPTION
**Pull request by pulsejet**
This will likely conflict/merge with #376

image

### CODE REVIEW

**Comment by RaymondHuang210129** [comment]
I believe this approach is better than #376 . Thanks for having this feature available.

**Comment by pulsejet** [comment]
> I believe this approach is better than #376 . Thanks for having this feature available.

They're somewhat orthogonal (at least the implementation). We still need the map regardless.

**Comment by RaymondHuang210129** [comment]
The `places-setup` command seems to break the PHP memory limit during the execution. 
My testing environment has PHP version 8.1.14 and a memory limit of 512MB.
```
Inserted 25000 places, 320.5/s, ETA: 1904s, Last: Osborne
Inserted 25500 places, 322.8/s, ETA: 1889s, Last: Stanford
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/lib/private/DB/BacktraceDebugStack.php on line 31
```

**Comment by pulsejet** [comment]
Try 2GB
```bash
PHP_MEMORY_LIMIT=2G php occ memories:places-setup
```

**Comment by thrillfall** [comment]
i am just running the index and can already see my holiday locations in the tiles and i just wanted to say: THANK YOU!!! This is so awesome!! :heart_decoration:

**Pull request merged**
